---
# config-specific task file for l2tp

- name: Create config and secrets fragment directories
  file:
    path: "{{ l2tp_config_base }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - ppp
    - xl2tpd

- name: Configure l2tp server settings
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ l2tp_config_base }}/{{ item.dir }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - filename: xl2tpd.conf
      dir: xl2tpd
    - filename: options.xl2tpd
      dir: ppp
  when:
    - l2tp_config.is_server is defined
    - l2tp_config.is_server
  notify:
    restart l2tp

- name: Configure l2tp server settings
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ l2tp_config_base }}/{{ item.dir }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - filename: chap-secrets
      dir: ppp
  when:
    - l2tp_config.is_server is defined
    - l2tp_config.is_server
    - not l2tp_config.use_radius
  notify:
    restart l2tp

- name: Configure l2tp client settings
  template:
    src: "{{ item.src_filename }}.j2"
    dest: "{{ l2tp_config_base }}/{{ item.dir }}/{{ item.dest_filename }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - src_filename: xl2tpd.conf
      dest_filename: xl2tpd.conf
      dir: xl2tpd
    - src_filename: options.xl2tpd
      dest_filename: options.xl2tpd.client
      dir: ppp
  when: (l2tp_config.is_server is not defined or l2tp_config.is_server == false)
  notify:
    restart l2tp

